# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df86a489f3141c48803130985d8aebbb3e3a895c86e03131109f0cab561c354664d5c5b1a37046b5b043994c11f1e89bea0978cbc370e0a3040663b417b86e8

test:
  secret_key_base: 91f850fd9930c6f64b55afd9c04532ed4b61bfcabed989a288d424fc176362d5f84886016e5568a8addf7b517b8ad7e5012021e2505d0cf27d9913d7c2e77fa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
